# I am a workflow that demonstrates how to trigger on a PR. I can be used in conjunction with a branch protection rule.
# This workflow should be disabled before the start of the presentation, and enabled when needed

name: Demo 05 - Pull Request

on:
  pull_request:
    branches: 
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  pr-check:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "I do a check on your PR"
      
    # COMMENT OUT AT BEGINNING OF DEMO
    - name: Fail This Step
      run: exit 1 
